### PR TITLE
Upgrade simple-icons to 4.18.0

### PR DESCRIPTION
**Pull request by florian-lefebvre**

### CODE REVIEW

**Comment by noahlitvin** [comment]
Thanks for this! When I run `yarn build`, I'm seeing the following error:

```
> vue-simple-icons@4.7.0 build:icons /Users/noahlitvin/Development/vue-simple-icons
> node build && babel src/components -d icons

SyntaxError: /Users/noahlitvin/Development/vue-simple-icons/src/components/HiveIcon.js: Legacy octal literals are not allowed in strict mode (26:2)

  24 |     return <svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 24 24" {...ctx.data}><title>Hive icon</title><path d="M6.076 1.637a.103.103 0 00-.09.05L.014 11.95a.102.102 0 000 .104l6.039 10.26c.04.068.14.068.18 0l5.972-10.262a.102.102 0 00-.002-.104L6.166 1.687a.103.103 0 00-.09-.05zm2.863 0c-.079 0-.13.085-.09.154l5.186 8.967a.105.105 0 00.09.053h3.117c.08 0 .13-.088.09-.157l-5.186-8.966a.104.104 0 00-.09-.051H8.94zm5.891 0a.102.102 0 00-.088.154L20.656 12l-5.914 10.209a.102.102 0 00.088.154h3.123a.1.1 0 00.088-.05l5.945-10.262a.1.1 0 000-.102L18.041 1.688a.1.1 0 00-.088-.051H14.83zm-.79 11.7a.1.1 0 00-.089.052l-5.101 8.82c-.04.069.01.154.09.154h3.117a.104.104 0 00.09-.05l5.1-8.82a.103.103 0 00-.09-.155h-3.118z"/></svg>
  25 |   }
> 26 | } 00-5.511 0L6.495.933c-.294.03-.715.055-.99.14-.28.092-.605.355-.605.807 0 .39.257.702.605.806.281.08.696.074.99.074h11.01c.293 0 .709.006.99-.074a.835.835 0 00.605-.806c0-.452-.324-.715-.605-.807-.275-.085-.697-.11-.99-.14zm6.037 6.767c.3-.019.709-.037.99-.116a.84.84 0 000-1.614c-.281-.085-.69-.073-.99-.073H3.214c-.3 0-.709-.012-.99.073a.84.84 0 000 1.614c.281.079.69.097.99.116l7.808.556c.642.042 1.308.042 1.943 0zm1.62 4.242c.513-.08.708-.104.989-.202.354-.121.605-.409.605-.806a.84.84 0 00-.605-.806c-.28-.086-.69-.019-.99.012l-9.232.929c-.776.079-1.582.079-2.358 0l-9.22-.93c-.3-.03-.715-.097-.99-.011a.84.84 0 00-.605.806c0 .397.25.685.605.806.275.092.476.123.99.202l8.823 1.418c1.038.165 2.12.165 3.158 0Z"/></svg>
     |   ^
  27 |   }
  28 | }
    at Object.raise (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:6344:17)
    at Object.readNumber (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:7194:14)
    at Object.getTokenFromCode (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:6966:14)
    at Object.getTokenFromCode (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:3631:18)
    at Object.getTokenFromCode (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:2306:20)
    at Object.nextToken (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:6542:12)
    at Object.next (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:6482:10)
    at Object.eat (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:6487:12)
    at Object.parseObj (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:9130:18)
    at Object.parseExprAtom (/Users/noahlitvin/Development/vue-simple-icons/node_modules/@babel/parser/lib/index.js:8774:21) {
  pos: 1318,
  loc: Position { line: 26, column: 2 },
  code: 'BABEL_PARSE_ERROR'
}
```

Could you help resolve this as well?

**Comment by florian-lefebvre** [comment]
Now there is another issue:
```bash
×  (babel) F:\CONTENT\DEVELOPPEMENT\WEB\PERSO\vue-simple-icons\src\index.js: `HandshakeIcon` has already been exported. Exported identifiers must be unique. (1435:9)
```
because some Icons have the same name: https://simple-icons.github.io/simple-icons-website/?q=handshake

**Comment by florian-lefebvre** [comment]
I'm investigating

**Comment by florian-lefebvre** [comment]
I didn't manage to fix it

**Pull request closed without merging**
